kind: DataProtectionApplication
apiVersion: oadp.openshift.io/v1alpha1
metadata:
 name: velero-sample
 namespace: openshift-adp
spec:
 backupLocations:
   - velero:
       config:
         profile: "default"
          region: minio
          s3Url: <url> 
          insecureSkipTLSVerify: "true"
          s3ForcePathStyle: "true"
        provider: aws
        default: true
        credential:
          key: cloud
          name: cloud-credentials 
        objectStorage:
          bucket: <bucket_name> 
          prefix: <prefix> 
  configuration:
   restic:
     enable: true
   velero:
     defaultPlugins:
       - openshift
       - aws
       - csi
