kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-03
  namespace: application-03
  labels:
    app: app-03
    app.kubernetes.io/component: app-03
    app.kubernetes.io/instance: app-03
    app.kubernetes.io/name: app-03
    app.openshift.io/runtime: httpd
    app.openshift.io/runtime-version: 2.4-el7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-03
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-03
        deployment: app-03
    spec:
      volumes:
        - name: pvc-app03
          persistentVolumeClaim:
            claimName: pvc-app03
      containers:
        - name: app-03
          image: >-
            image-registry.openshift-image-registry.svc:5000/application-03/app-03@sha256:b2128f19632a74853a21e26cc997dc0d49b43e10dabc89c10e77addad03f3cef
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: pvc-app03
              mountPath: /mnt
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
