kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-app03
  namespace: application-03
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: thin-csi
  volumeMode: Filesystem
