kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-app04
  namespace: application-04
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: thin-csi
  volumeMode: Filesystem
