apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-app
    app.kubernetes.io/component: httpd-app
    app.kubernetes.io/instance: httpd-app
    app.kubernetes.io/name: httpd-app
    app.openshift.io/runtime: httpd
    app.openshift.io/runtime-version: 2.4-el7
  name: httpd-app
  namespace: application-01
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpd-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: httpd-app
        deploymentconfig: httpd-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/application-01/httpd-app@sha256:70c50304362079b33cc7eb66958c673bd37a2047f7e05cc94031660cf3e45b2f
        imagePullPolicy: Always
        name: httpd-app
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
~                                          
