apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd-app
    app.kubernetes.io/component: httpd-app
    app.kubernetes.io/instance: httpd-app
    app.kubernetes.io/name: httpd-app
    app.openshift.io/runtime: httpd
    app.openshift.io/runtime-version: 2.4-el7
  name: httpd-app
  namespace: application-01
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: httpd-app
    deploymentconfig: httpd-app
  sessionAffinity: None
  type: ClusterIP
~                          
