kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-app02
  namespace: application-02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: thin-csi
  volumeMode: Filesystem
